const APP_KEY = "E15CZUsgKRSaV4DC3SxrcQZMR";
const APP_SECRET = "htFWVdbfH9myRIjtr6XHQe6FOevrvv6jxI6tbPJ7yAUJr33PIe";
const ACCESS_TOKEN = "1735008453569941504-fxZgSYIAXZ0iIjqnuROZjjXD1vMsXT";
const ACCESS_SECRET = "a10NbWTaWEkYCAGoLhpjfxkrkdRGDBTjaDCcgWtafTIYZ";
const GEMINI_API_KEY = "AIzaSyAAML2Mw40UDU5F4NXYBPrZPVXB3piLRS4";
const SECRETS = {
  APP_KEY,
  APP_SECRET,
  ACCESS_TOKEN,
  ACCESS_SECRET,
  GEMINI_API_KEY,};
module.exports = SECRETS;
